### ISSUE TITLE
User story:  WELL - Batch update on attributes

### ISSUE THREAD

**Issue by thomash1972** [equinor/witsml-explorer#179]
As a Data Manager
I want to Multi Select MANY well objects, and batch update important attributes
so that I can clean up MANY Wellbores in 1 click

### Acceptance criteria ###
- [ ] I can select many wellbores, right click, and edit values in the property dialogue
- [ ] After the edit, all well objects selected have the edited attribute applied

Also, here are a few points that need to be addressed:
- [ ] Constraint 1
- [ ] Constraint 2

### Resources ###
-  Kongsberg Digital

**Comment by Pascal62223** [comment]
Actual well explorer list is limited to '30' visible wells. How do we foresee the user to be able to select the wells he/she wants to edit  together (especially when the one he/she wants are not listed, or only some of them are)? 
Should the actual filter be extended to support smart filtering based on series of attributes (e.g. Name = "*UA*" and Company = "XyZ" and Type = "Well" etc ..). 
 Some UX work will be required in support of that card before implementation (front end). Back-end is independent so that should be fine.

**Comment by HakonHesselberg** [comment]
> Actual well explorer list is limited to '30' visible wells. How do we foresee the user to be able to select the wells he/she wants to edit together (especially when the one he/she wants are not listed, or only some of them are)?

I added issue 304 to address this.
