### ISSUE TITLE
Open Channel stream for 1 or several timebased curves (streaming window)

### ISSUE THREAD

**Issue by janburak** [equinor/witsml-explorer#1899]
Select curves in a TIME log.

Right click → Open – ETP datastream

RIPS will then Open a Data content window similar to the current Right click → Open functionality.

But the difference is that WE will use ETP to setup a streaming of the datasets to the Data Content window. 

The user can start / stop the streaming in the data content window. Data will continously scroll up when the stream is started.

Probably need a timeout after x minutes ?

From Jira WE-652

**Comment by ThomasHalland** [comment]
Low Priority since it requires a lot of development. But very interesting if someone wants to start.....

**Comment by ThomasHalland** [comment]
MORE DETAILS.

- The stream functionality is only available for Logs which are actively growing.

- Whan you are displaying values from a set of curves, you have a Stream switch available which can be turned on / off (similar to the Show Graph switch). 

When you turn on the STREAM switch, the  the selected curve view will refresh and scroll to the end with the latest values at the bottom of the view. Every X seconds Wex will look for data with new values compared to the latest end_index. If new values are found they will be plotted at the bottom and the rest of the values will be scrolled upwards (so that the latest values with the highest index are always at the bottom.

- The start index / end index normally selectable by the user in the heading, will be greyed out since the STREAM mode automatically forces the user to view the last available interval for the channels. 

- The user will "loose" the selected interval, since the STREAM mode automatically jumps to the highest index.

- It is OK for the STREAM mode to be "append only" which means that it will only look for data values deeper than the end index from the last cycle.

A typical cycle will be between 3 - 5 seconds.

If possible the new datasets added to the curve in each cycle shall be displayed with a green color, so that it is easy to get a visual view of how many new rows that are added for each cycle. 
In the next cycle again, the new data from the previous cycle will turn to normal color, so that it is only data from the last cycle which will be green.

- When the user turns off the STREAM mode, a full refresh of the selected curves is performed similar to the first time the curves are opened.
