### ISSUE TITLE
🐛 Login dialog does not appear for a server if cancelled first

### ISSUE THREAD

**Issue by Pascal62223** [equinor/witsml-explorer#190]
**:bug: Describe the bug**
Login dialog does not appear if select same server after a cancel operation on the login dialog

**To Reproduce**
![image](https://user-images.githubusercontent.com/77442348/108586234-07e31080-7388-11eb-8ebd-c3af5683c39e.png)

The step by step screenshot below explain the issue.

**Expected behavior**
When select a server from the dropdown list, if not already connected, the login dialog box must be displayed.

**Screenshots**

![WE-bug-logion-dialog](https://user-images.githubusercontent.com/77442348/108586274-45479e00-7388-11eb-8cee-e167b2b3388d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version : Version 88.0.4324.150 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by steinsiv** [comment]
Thanks!,  

That behaviour is not entirely intuitive. The issue is on the todolist already i believe  

Btw: There is one "workaround" that I noticed after a while. It is possible to click the link right below the dropdown to reopen the dialog directly without changing providers.. 

This "workaround" is not optimal, not obvious either... Just wanted to share the info

<img width="504" alt="Screenshot 2021-02-23 at 19 21 40" src="https://user-images.githubusercontent.com/1442452/108891930-974e2500-760f-11eb-9d5b-db3d2e7b1e0e.png">

**Comment by Pascal62223** [comment]
Whaoo.. nice trick :-D ....
