### ISSUE TITLE
Investigate options for deserializing ObjectOnWellbore

### ISSUE THREAD

**Issue by eliasbruvik** [equinor/witsml-explorer#2176]
When trying to deserialize an ObjectOnWellbore to the appropriate subclass, the `ObjectOnWellboreConverter` assumes that the input object has a "objectType" property added in the received JSON. The objectType property is not added to the objectOnWellbore models in the frontend or the API, so you manually have to add it before sending the request to the API. 

Investigate if we should add objectType to the models, or if there are better ways to deserialize it to the correct subclass.

**Comment by vaclavbasniar** [comment]
Reliable automated extraction of objects' type name is not possible in JS/TS/React (see e.g.: https://timmousk.com/blog/typescript-get-class-name/, or https://www.beyondjava.net/constructor-name).

More reliable solution could be using model entities as classes with objectType property, for example:
abstract class ObjectOnWellbore {
    objectType: string;
    constructor() {
        this.objectType = 'ObjectOnWellbore';
    }
}

class BhaRun extends ObjectOnWellbore {
  constructor() {
    super();
    this.objectType = 'BhaRun';
  }
}
However, the downside is that the class must be instantiated, e.g. _new BhaRun()_, otherwise the type name wouldn't be set. In case the object is retyped, e.g. like _{} as BhaRun_, _objectType_ will of course return _undefined_ and _objectType_ would have been set manually anyway.

**Comment by eliasbruvik** [comment]
Sorry for a late reply. If I understand you correctly, there are other ways to do it, but none of which are really a "good" solution? Do you recommend just leaving it as is?

**Comment by vaclavbasniar** [comment]
Yes, I think the solutions are more or less interchangeable in terms of boilerplate and reliability. If the _objectType_ property is not needed elsewhere, I'd suggest the current implementation is a better solution.

**Comment by eliasbruvik** [comment]
Sounds reasonable for me. I'll just close this then.
