### ISSUE TITLE
👉 Filter on Live Objects

### ISSUE THREAD

**Issue by HakonHesselberg** [equinor/witsml-explorer#237]
**👉 Is your feature request related to a problem? Please describe.**
This task is related to User Story #177

Users should be able to filter on **Live Objects** so they can work only on WELLS / WELLBORES / LOGS containing **Live Objects**.

**Describe the solution you'd like**
A filter option or check box similar to what is seen in the picture (RT Only).

When the filter is applied, only WELLS / WELLBORES / LOGS containing **Live Objects** are displayed.

![image](https://user-images.githubusercontent.com/1553016/109826356-fe389300-7c3a-11eb-960a-dbc598e31e2f.png)

**Describe alternatives you've considered**
Currently no alternatives, but open to suggestions

**Additional context**

**Comment by marmid74** [comment]
Will discuss with UI designer asap, will notify you.

**Comment by Pascal62223** [comment]
As new objects becomes Live\stop being live, would the 'tree' be automatically updated or should the user force a refresh ?
I do believe an option should allow user to have an 'auto-update of filter' configurable (update frequency) .
The option can be turned Off so that screen is not flickering every 'n' seconds,  but when On user view is what the state of the objects are.

That being said, maybe such feature is crossing the line between '(static) data management' and 'RT surveillance'. So maybe out-of-scope ?

**Comment by marmid74** [comment]
**The criteria for Live status:**
wellbore object: isActive ===true  && Log/Trajectory/<object> object: objectGrowing === true

**Comment by marmid74** [comment]
**Response  to question from  Pascal:** 
We need to raise a discussion in community: Should WE do auto-refresh of wellbore status (live status). If a new wellbore isActive===true, or an existing wellbore suddenly turns isActive, should it automatically show up in the user interface (UI change )
