### ISSUE TITLE
🐛 Selecting multiple rows with shift is unreliable in VirtualizedContentTable

### ISSUE THREAD

**Issue by aszalos-roland** [equinor/witsml-explorer#382]
**:bug: Describe the bug**
Does not select what the user sees if the order is different than the default. In code the unsorted data is used for selection which causes this behaviour.

**To Reproduce**
1. Open some mnemonics from a log
2. Order the table differently
3. Using shift + click select some rows
4. Selection is not the desired selection

**Expected behavior**
A selection happens to the wanted item range.

**Screenshots**
Behaviour:
![selection bug](https://user-images.githubusercontent.com/76997928/117663543-0d8b0e00-b1a1-11eb-957c-02383e43f4d9.gif)

**Desktop (please complete the following information):**
 - any browser
 - main branch

**Smartphone (please complete the following information):**
 - any device
 - main branch

**Comment by marmid74** [comment]
@aszalos-roland - could you please detail out the bug description, as I dont understand the description above/or I am not able to reproduce the error based on your description above.

**Comment by aszalos-roland** [comment]
> @aszalos-roland - could you please detail out the bug description, as I dont understand the description above/or I am not able to reproduce the error based on your description above.

updated the description

**Comment by marmid74** [comment]
Not able to reproduce the same scenario as described initially. However,  the alternation  between "click"  and   "click + shift" seem to be vital. Keeping shift down while multiple random order clicks might cause unexpected toggle on/of mnemonics in the list.

Expected Behaviour (Start all scenarios with no selected mnenonics)
**Scenario 1:** Select  mnemonic "A" (click) and then select another "D" (click + shift) => expect toggle on all mnemonics between (B and C)
**Scenario 2:** Select mnemonic "A" (click), select "F" (click), select "C" (click + shift) =>  expect toggle mnemonics (D and E)
